after-login-command = []
after-startup-command = []
start-at-login = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
automatically-unhide-macos-hidden-apps = true

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
ctrl-alt-shift-cmd-tab = 'workspace-back-and-forth'
ctrl-alt-shift-cmd-left = 'focus left'
ctrl-alt-shift-cmd-down = 'focus down'
ctrl-alt-shift-cmd-up = 'focus up'
ctrl-alt-shift-cmd-right = 'focus right'
ctrl-alt-shift-cmd-semicolon = 'mode service'
ctrl-alt-shift-cmd-space = 'mode move'
ctrl-alt-shift-cmd-a = 'workspace A'
ctrl-alt-shift-cmd-b = 'workspace B'
ctrl-alt-shift-cmd-c = 'workspace C'
ctrl-alt-shift-cmd-d = 'workspace D'
ctrl-alt-shift-cmd-e = 'workspace E'
ctrl-alt-shift-cmd-f = 'workspace F'
ctrl-alt-shift-cmd-g = 'workspace G'
ctrl-alt-shift-cmd-i = 'workspace I'
ctrl-alt-shift-cmd-m = 'workspace M'
ctrl-alt-shift-cmd-n = 'workspace N'
ctrl-alt-shift-cmd-o = 'workspace O'
ctrl-alt-shift-cmd-p = 'workspace P'
ctrl-alt-shift-cmd-q = 'workspace Q'
ctrl-alt-shift-cmd-r = 'workspace R'
ctrl-alt-shift-cmd-s = 'workspace S'
ctrl-alt-shift-cmd-t = 'workspace T'
ctrl-alt-shift-cmd-u = 'workspace U'
ctrl-alt-shift-cmd-v = 'workspace V'
ctrl-alt-shift-cmd-w = 'workspace W'
ctrl-alt-shift-cmd-x = 'workspace X'
ctrl-alt-shift-cmd-y = 'workspace Y'
ctrl-alt-shift-cmd-z = 'workspace Z'

[mode.move.binding]
ctrl-alt-shift-cmd-space = 'mode main'

left = 'focus left'
down = 'focus down'
up = 'focus up'
right = 'focus right'
shift-left = 'move left'
shift-down = 'move down'
shift-up = 'move up'
shift-right = 'move right'

minus = 'resize smart -50'
equal = 'resize smart +50'

a = 'workspace A'
b = 'workspace B'
c = 'workspace C'
d = 'workspace D'
e = 'workspace E'
f = 'workspace F'
g = 'workspace G'
i = 'workspace I'
m = 'workspace M'
n = 'workspace N'
o = 'workspace O'
p = 'workspace P'
q = 'workspace Q'
r = 'workspace R'
s = 'workspace S'
t = 'workspace T'
u = 'workspace U'
v = 'workspace V'
w = 'workspace W'
x = 'workspace X'
y = 'workspace Y'
z = 'workspace Z'
shift-a = 'move-node-to-workspace A'
shift-b = 'move-node-to-workspace B'
shift-c = 'move-node-to-workspace C'
shift-d = 'move-node-to-workspace D'
shift-e = 'move-node-to-workspace E'
shift-f = 'move-node-to-workspace F'
shift-g = 'move-node-to-workspace G'
shift-i = 'move-node-to-workspace I'
shift-m = 'move-node-to-workspace M'
shift-n = 'move-node-to-workspace N'
shift-o = 'move-node-to-workspace O'
shift-p = 'move-node-to-workspace P'
shift-q = 'move-node-to-workspace Q'
shift-r = 'move-node-to-workspace R'
shift-s = 'move-node-to-workspace S'
shift-t = 'move-node-to-workspace T'
shift-u = 'move-node-to-workspace U'
shift-v = 'move-node-to-workspace V'
shift-w = 'move-node-to-workspace W'
shift-x = 'move-node-to-workspace X'
shift-y = 'move-node-to-workspace Y'
shift-z = 'move-node-to-workspace Z'

shift-tab = 'move-workspace-to-monitor --wrap-around next'

slash = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
