after-login-command = []
after-startup-command = []
start-at-login = true

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
ctrl-alt-cmd-shift-tab = 'workspace-back-and-forth'
ctrl-alt-cmd-shift-left = 'focus left'
ctrl-alt-cmd-shift-down = 'focus down'
ctrl-alt-cmd-shift-up = 'focus up'
ctrl-alt-cmd-shift-right = 'focus right'
ctrl-alt-cmd-shift-semicolon = 'mode service'
ctrl-alt-cmd-shift-slash = 'layout tiles horizontal vertical'
ctrl-alt-cmd-shift-comma = 'layout accordion horizontal vertical'
ctrl-alt-cmd-shift-space = 'mode move'
ctrl-alt-cmd-shift-1 = 'workspace 1'
ctrl-alt-cmd-shift-2 = 'workspace 2'
ctrl-alt-cmd-shift-3 = 'workspace 3'
ctrl-alt-cmd-shift-4 = 'workspace 4'
ctrl-alt-cmd-shift-5 = 'workspace 5'
ctrl-alt-cmd-shift-6 = 'workspace 6'
ctrl-alt-cmd-shift-7 = 'workspace 7'
ctrl-alt-cmd-shift-8 = 'workspace 8'
ctrl-alt-cmd-shift-9 = 'workspace 9'
ctrl-alt-cmd-shift-a = 'workspace A'
ctrl-alt-cmd-shift-b = 'workspace B'
ctrl-alt-cmd-shift-c = 'workspace C'
ctrl-alt-cmd-shift-d = 'workspace D'
ctrl-alt-cmd-shift-e = 'workspace E'
ctrl-alt-cmd-shift-f = 'workspace F'
ctrl-alt-cmd-shift-g = 'workspace G'
ctrl-alt-cmd-shift-i = 'workspace I'
ctrl-alt-cmd-shift-m = 'workspace M'
ctrl-alt-cmd-shift-n = 'workspace N'
ctrl-alt-cmd-shift-o = 'workspace O'
ctrl-alt-cmd-shift-p = 'workspace P'
ctrl-alt-cmd-shift-q = 'workspace Q'
ctrl-alt-cmd-shift-r = 'workspace R'
ctrl-alt-cmd-shift-s = 'workspace S'
ctrl-alt-cmd-shift-t = 'workspace T'
ctrl-alt-cmd-shift-u = 'workspace U'
ctrl-alt-cmd-shift-v = 'workspace V'
ctrl-alt-cmd-shift-w = 'workspace W'
ctrl-alt-cmd-shift-x = 'workspace X'
ctrl-alt-cmd-shift-y = 'workspace Y'
ctrl-alt-cmd-shift-z = 'workspace Z'

[mode.move.binding]
ctrl-alt-cmd-shift-space = 'mode main'
left = 'move left'
down = 'move down'
up = 'move up'
right = 'move right'

minus = 'resize smart -50'
equal = 'resize smart +50'

1 = 'move-node-to-workspace 1'
2 = 'move-node-to-workspace 2'
3 = 'move-node-to-workspace 3'
4 = 'move-node-to-workspace 4'
5 = 'move-node-to-workspace 5'
6 = 'move-node-to-workspace 6'
7 = 'move-node-to-workspace 7'
8 = 'move-node-to-workspace 8'
9 = 'move-node-to-workspace 9'
a = 'move-node-to-workspace A'
b = 'move-node-to-workspace B'
c = 'move-node-to-workspace C'
d = 'move-node-to-workspace D'
e = 'move-node-to-workspace E'
f = 'move-node-to-workspace F'
g = 'move-node-to-workspace G'
i = 'move-node-to-workspace I'
m = 'move-node-to-workspace M'
n = 'move-node-to-workspace N'
o = 'move-node-to-workspace O'
p = 'move-node-to-workspace P'
q = 'move-node-to-workspace Q'
r = 'move-node-to-workspace R'
s = 'move-node-to-workspace S'
t = 'move-node-to-workspace T'
u = 'move-node-to-workspace U'
v = 'move-node-to-workspace V'
w = 'move-node-to-workspace W'
x = 'move-node-to-workspace X'
y = 'move-node-to-workspace Y'
z = 'move-node-to-workspace Z'

shift-tab = 'move-workspace-to-monitor --wrap-around next'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
